### ISSUE TITLE
Error - Could not update data

### ISSUE THREAD

**Issue by kloggy** [custom-components/breaking_changes#3]
## Version of the custom_component
![image](https://user-images.githubusercontent.com/38220016/57841149-f1c31c00-77c1-11e9-8efd-5b247119fe03.png)

## Describe the bug
I'm getting an error in my log. (see below)
I have Sonos configured so should have at least one breaking change.
This error only seems to have appeared since yesterday when 0.93 was released

![image](https://user-images.githubusercontent.com/38220016/57841410-639b6580-77c2-11e9-97e6-305982919799.png)

## `custom_updater` configuration

```
custom_updater:
  track:
    - components
    - cards
    - python_scripts
  component_urls:
    - https://raw.githubusercontent.com/briis/smartweather/master/custom_updater.json
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/rdehuyss/homeassistant-lovelace-google-calendar-card/master/custom_updater.json
    - https://raw.githubusercontent.com/iammexx/home-assistant-config/master/ui/darksky/version.json
    - https://raw.githubusercontent.com/MizterB/lovelace-secondaryinfo-entity-row/master/custom_cards.json
    - https://raw.githubusercontent.com/malcolmrigg/WizardClock/master/repo.json
```

# Add configuration here
LOVELACE
```
      #=============
      #=== Software
      #=============
      - type: custom:vertical-stack-in-card
        cards:
          - type: custom:card-modder
            style:
              background: transparent
              border-radius: 0px
            card:
              type: glance
              title: '-- Software --'
              columns: 3
              entities:
                - entity: sensor.installed_version
                  name: Installed Version
                  icon: mdi:home-assistant
                - entity: sensor.latest_available_version
                  name: Latest Version
                  icon: mdi:home-assistant
                - entity: binary_sensor.potential_breaking_changes
                  name: Breaking Changes
      #            icon: mdi:home-assistant

          - type: custom:card-modder
            style:
              background: transparent
              border-radius: 0px
            card:
              type: entities
              entities:
                - entity: sensor.ha_uptime
                  icon: mdi:home-assistant

                - entity: sensor.tasmota_current_version
                  name: Sonoff / Tasmota Current Version
                  icon: mdi:alpha-s-box-outline
```

## Debug log
```2019-05-16 09:49:50 ERROR (MainThread) [custom_components.breaking_changes] Could not update data - Expecting value: line 1 column 1 (char 0)```

##Add your logs here.
N/A
