### ISSUE TITLE
Attribute not show the changes in json format 

### ISSUE THREAD

**Issue by poudenes** [custom-components/breaking_changes#32]
its not show the breaking changes in json:

```
changes:
  - title: Automation
    integration: homeassistant
    prlink: 'https://github.com/home-assistant/core/pull/41261'
    doclink: 'https://www.home-assistant.io/integrations/homeassistant'
    description: ' State conditions with attribute specified: When testing against a non-string attribute value, you now need to specify the value in your configuration in the same type as it is in the attribute (instead of as a string).'
  - title: 'HomeKit Controller, Plant, SmartThings, Xiaomi'
    integration: homeassistant
    prlink: 'https://github.com/home-assistant/core/pull/40171'
    doclink: 'https://www.home-assistant.io/integrations/homeassistant'
    description: ' Some integrations (`homekit_controller`, `plant`, `smartthings` and `xiaomi_miio`) previously used `lux` as their unit of measurement for entities that covered illuminance. Now, these entities use `lx` as their unit of measurement to be consistent with other integrations.This could be a breaking change for using such entities in, for example, `influxdb`.'
  - title: Logbook
    integration: logbook
    prlink: 'https://github.com/home-assistant/core/pull/40070'
    doclink: 'https://www.home-assistant.io/integrations/logbook'
    description: ' Message and domain are now removed from the logbook `state_changed` events.These are now handled by the frontend as we move closer to making the logbook localized.'
  - title: TekSavvy
    integration: homeassistant
    prlink: 'https://github.com/home-assistant/core/pull/40762'
    doclink: 'https://www.home-assistant.io/integrations/homeassistant'
    description: ' The TekSavvy integration has been removed. The API that was used by this integration is no longer available.'
  - title: MQTT
    integration: mqtt
    prlink: 'https://github.com/home-assistant/core/pull/41361'
    doclink: 'https://www.home-assistant.io/integrations/mqtt'
    description: ' MQTT Discovery is now enabled by default.'
  - title: Templates - Auto-updating now()
    integration: homeassistant
    prlink: 'https://github.com/home-assistant/core/pull/41147'
    doclink: 'https://www.home-assistant.io/integrations/homeassistant'
    description: ' The `entity_id:` attribute was recently removed from template entities because the templates are now able to find all referenced entities automatically. This removal introduced a new problem where templates using the current time could no longer use `entity_id: sensor.time` to ensure periodic updates.With apologies to those who have spent the last couple of releases adding workarounds to their templates, we are now introducing an auto-refresh feature to time-based templates.It is thus no longer necessary to reference `sensor.time`, `sensor.date` or manually update template entities when `now()` or `utcnow()` is present in the template.The template will automatically be updated when:Please note, if you have a time-based template where you <em>do not</em> want it to update periodically it will now have to be reworked to not use `now()`.'
  - title: Templates - Native types (BETA)
    integration: homeassistant
    prlink: 'https://github.com/home-assistant/core/pull/41227'
    doclink: 'https://www.home-assistant.io/integrations/homeassistant'
    description: ' Template results can now rendered to native Python types, but only when the legacy template rendering is disabled.<strong>This feature will be opt-in for this release, the breaking changes below only apply if you explicitly enable this new feature.</strong>A template would always result in a string (text). This made it hard to use things like lists, or numbers as a result of a template. For example, returning a list of entities or a RGB/HS/XY color.This change may impact your existing templates, as templates now can return other types; For example, string, float, integer, boolean, lists or dictionaries.The following templates can be impacted by this:'
  - title: Templates - Rate limits
    integration: homeassistant
    prlink: 'https://github.com/home-assistant/core/pull/42004'
    doclink: 'https://www.home-assistant.io/integrations/homeassistant'
    description: ' Previously we implemented a rate limit of 1 update per minute for `states.DOMAIN` in templates. This has been changed to an update once every second.Templates using `states` (without a domain) still have a rate limit of 1 update per minute.'
versions:
  - 116
  - 117
friendly_name: Potential breaking changes
icon: 'mdi:package-up'
templates:
  icon_color: >-
    if (state === 'on') return 'rgba(251,214,67,1)'; return
    'rgba(71,116,157,1)';
icon_color: 'rgba(71,116,157,1)'

```
